const translations = {
    fr: {
        "nav.home": "Accueil",
        "nav.about": "Qui sommes-nous",
        "nav.services": "Nos services",
        "nav.portfolio": "Nos réalisations",
        "nav.ongoing": "En cours de réalisation",
        "nav.careers": "Offres d'emploi",
        "nav.logo": "EPHOD Consulting",
        
        "nav.drop_vision": "Notre Vision",
        "nav.drop_vision_sub": "Valeurs & identité",
        "nav.drop_team": "Notre Équipe",
        "nav.drop_team_sub": "Nos experts dédiés",
        "nav.drop_strat_short": "Advisory Stratégique",
        "nav.drop_strat_sub2": "Gouvernance & M&E",
        "nav.drop_digital_short": "Digitalisation & SIG",
        "nav.drop_digital_sub2": "Innovation analytique",
        "nav.drop_public_short": "Études & Évaluations",
        "nav.drop_public_sub2": "Standards OCDE-CAD",
        
        "menu.home_head": "En-tête",
        "menu.home_head_sub": "Retour au début",
        "menu.home_news": "Dernières missions",
        "menu.home_news_sub": "Notre actualité récente",
        "menu.home_partners": "Réseau de confiance",
        "menu.home_partners_sub": "Nos collaborateurs",
        
        "menu.about_vision": "Notre Vision",
        "menu.about_vision_sub": "Valeurs & identité",
        "menu.about_mission": "Notre Mission",
        "menu.about_mission_sub": "Engagements EPHOD",
        "menu.about_team": "Notre Équipe",
        "menu.about_team_sub": "Experts pluridisciplinaires",
        
        "menu.srv_audit": "Audit & Assurance",
        "menu.srv_audit_sub": "Expertise complète",
        "menu.srv_cap": "Renforcement des Capacités",
        "menu.srv_cap_sub": "Formation & coaching",
        "menu.srv_support": "Support & Gestion",
        "menu.srv_support_sub": "Accompagnement de projets",
        "menu.srv_eval": "Évaluations Stratégiques",
        "menu.srv_eval_sub": "Mesures d'impact",
        
        "menu.port_lualaba": "Lualaba & Haut-Katanga",
        "menu.port_lualaba_sub": "Secteur minier",
        "menu.port_kivu": "Nord-Kivu",
        "menu.port_kivu_sub": "Risques & Protection",
        "menu.port_sud": "Sud-Kivu",
        "menu.port_sud_sub": "Évaluations PDM",
        
        "menu.ong_missions": "Missions Actuelles",
        "menu.ong_missions_sub": "Sur le terrain",
        "menu.ong_zones": "Zones d'accès complexe",
        "menu.ong_zones_sub": "Déploiements RDC",
        
        "menu.car_join": "Rejoindre l'équipe",
        "menu.car_join_sub": "Opportunités EPHOD",
        "menu.car_network": "Réseau d'experts",
        "menu.car_network_sub": "Consultants indépendants",
        
        "menu.contact_offices": "Nos Bureaux",
        "menu.contact_offices_sub": "Kinshasa, Goma, Beni",
        "menu.contact_write": "Nous écrire",
        "menu.contact_write_sub": "Demandes & Support",
        
        "hero.eyebrow": "CONSEIL • INNOVATION • IMPACT",
        "hero.line0": "EPHOD CONSULTING",
        "hero.line1": "RENFORCER les conditions d'un",
        "hero.line2": "DÉVELOPPEMENT DURABLE.",
        "hero.line3": "MESURER l'impact pour",
        "hero.line4": "AMÉLIORER les pratiques.",
        "hero.subtitle": "Un cabinet de conseil engagé à créer un impact social et économique mesurable dans les pays émergents.",
        "hero.scroll": "Découvrir",
        "hero.next": "Voir l'Impact",

        "home.services_label": "NOS DOMAINES",
        "home.services_title": "Une expertise <span>contextualisée</span>",
        "home.hero_srv_title": "Expertise de <span>Haut Niveau</span>",
        "home.stat1_label": "Missions Réussies",
        "home.stat2_label": "Experts Associés",
        "home.stat3_label": "Provinces Couvertes",
        "home.stat4_label": "% Satisfaction",
        "home.method_label": "Rigueur & Qualité",
        "home.method_title": "<span class='color-noir'>Standards</span> <span class='color-rouge'>Internationaux</span>",
        "home.method_title_part1": "Standards",
        "home.method_title_part2": "Internationaux",
        "home.method_desc": "Nos interventions sont guidées par les critères d'évaluation de l'OCDE-CAD et les standards de la CHS Alliance.",
        "home.m1_title": "OCDE-CAD",
        "home.m1_desc": "Pertinence, efficacité, efficience, impact et durabilité au cœur de nos études.",
        "home.m2_title": "CHS ALLIANCE",
        "home.m2_desc": "Engagement formel pour la redevabilité et la protection contre les abus (PSEA).",
        "home.about_desc": "EPHOD Consulting SARL — Cabinet de conseil congolais spécialisé dans l’évaluation indépendante, l’appui stratégique et le renforcement des capacités selon les standards internationaux (OCDE-CAD, CHS).",
        "home.intro_label": "PROFIL INSTITUTIONNEL",
        "home.acronym_tag": "EPHOD =",
        "home.acronym_meaning": "<span class='color-noir'>Expertise en Planification</span> <span class='color-rouge'>Humanitaire et Opérationnalisation du Développement</span>",
        "home.intro_quote": "« La rigueur méthodologique au service de la réduction de la pauvreté. »",
        "home.intro_title_black": "Expertise stratégique &",
        "home.intro_title_red": "analyse indépendante",
        "home.intro_btn": "+ EN SAVOIR PLUS",
        "home.services_heading": "<span class='color-noir'>CE QUE NOUS FAISONS</span> <span class='color-rouge'>POUR VOUS.</span>",
        "home.partners_label": "RÉSEAU DE CONFIANCE",
        "home.partners_title": "Nos Partenaires & Collaborateurs.",
        "home.partners_heading": "<span style='color: #111111;'>Nos Partenaires &amp;</span> <span style='background: linear-gradient(90deg, #8C1338, #FF2E2E); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; display: inline-block; margin-left: 8px;'>Collaborateurs.</span>",
        "home.news_label": "ACTUALITÉS",
        "home.news_title_line1": "RETROUVEZ ICI",
        "home.news_title_line2": "NOS DERNIÈRES",
        "home.news_title_line3": "ACTUALITÉS.",
        "home.news_title": "Dernières <span>Missions</span>",
        "home.news_btn": "Toutes nos actualités",
        "home.news_more": "En savoir plus",
        "home.news1_zone": "LUALABA & HAUT-KATANGA",
        "home.news1_title": "ProGERIM II — GIZ",
        "home.news1_desc": "Collecte et analyse de données relatives à la bonne gestion des revenus infranationaux du secteur minier en RDC.",
        "home.news2_zone": "NORD-KIVU — Kayna & Lubero",
        "home.news2_title": "Étude JRS 2026",
        "home.news2_desc": "Étude de marché et évaluation des risques de protection liés aux interventions en cash pour populations déplacées.",
        "home.news3_zone": "SUD-KIVU",
        "home.news3_title": "PDM Christian Aid",
        "home.news3_desc": "Post Distribution Monitoring — évaluation des résultats d'interventions cash dans les zones à accès complexe du Sud-Kivu.",

        "about.banner_title": "Expertise Locale, Standards Internationaux",
        "about.banner_sub": "Cabinet immatriculé (RCCM CD/KNG/RCCM/25-B-03958) dédié à la performance et la redevabilité en contextes fragiles.",
        "about.banner_title": "<span class='color-noir'>L'EXCELLENCE AU SERVICE</span> <span class='color-rouge'>DE L'IMPACT</span>",
        "about.banner_desc": "EPHOD Consulting déploie une expertise de pointe pour transformer les défis complexes en impacts durables. Une excellence opérationnelle aux standards mondiaux, même en contextes fragiles.",
        "about.values_title": "<span class='color-noir'>Nos Valeurs</span> <span class='color-rouge'>Fondamentales</span>",
        "about.vision_label": "Notre Vision",
        "about.vision_title": "<span class='color-noir'>Indépendance Analytique,</span> <span class='color-rouge'>Déploiement Agile</span>",
        "about.vision_p1": "EPHOD Consulting SARL se distingue par sa compréhension fine des dynamiques locales et sa capacité de déploiement opérationnel en environnements complexes, du Kasaï à l'Ituri.",
        "about.vision_p2": "Nous accompagnons nos partenaires (GIZ, UNICEF, UNHCR, SCI) tout au long du cycle de projet, produisant des analyses orientées vers l'amélioration durable de l'impact des interventions sociales et humanitaires.",
        "about.motto": "La rigueur méthodologique au service de la réduction de la pauvreté.",
        "about.val1_title": "Excellence",
        "about.val1_desc": "Nous maintenons les plus hauts standards professionnels dans chaque mission, alignés sur les référentiels OCDE-CAD et CHS.",
        "about.val2_title": "Indépendance",
        "about.val2_desc": "Nos évaluations sont rigoureuses, objectives et libres de tout conflit d'intérêt, garantissant une crédibilité totale pour nos partenaires.",
        "about.val3_title": "Impact",
        "about.val3_desc": "Chaque intervention vise des résultats mesurables et durables. Nous concevons des solutions adaptées aux réalités locales.",
        "about.val4_title": "Proximité",
        "about.val4_desc": "Nous opérons au cœur du terrain, même dans les zones à accès complexe, grâce à nos bureaux à Kinshasa, Goma et Beni.",
        "about.role_dg_desc": "Visionnaire et garante de l'excellence stratégique d'EPHOD Consulting.",
        "about.role_ops_desc": "Expert en coordination et déploiements terrain en environnements complexes.",
        "about.network_feat4_title": "Mobilité & Agilité",
        "about.network_feat4_desc": "Déploiement opérationnel agile en 48h sur tout le territoire national.",
        "about.conformity": "Engagement & Conformité",
        "about.network_label": "NOTRE CAPITAL HUMAIN",
        "about.network_title": "<span class='color-noir'>Réseau de</span> <span class='color-rouge'>+50 Experts</span>",
        "about.network_desc": "Au-delà de notre équipe permanente, EPHOD Consulting mobilise un pool d'experts associés de haut niveau spécialisés par secteurs : Santé, Études, Gouvernance Minière, WASH et Protection.",
        "about.network_feat1": "Experts Nationaux & Internationaux de haut niveau",
        "about.network_feat2": "Maîtrise complète des standards OCDE-CAD et du CHS",
        "about.network_feat3": "Capacité agile de déploiement en zones à accès complexe",
        "about.network_count_label": "Consultants Associés",
        "about.network_availability": "Disponibles pour des missions d'urgence et de développement sur tout le territoire national.",
        "about.team_label": "LEADERSHIP",
        "about.team_title": "<span class='color-noir'>Direction</span> <span class='color-rouge'>Stratégique</span>",
        "about.role_dg": "Gérante Principale",
        "about.role_expert_chef": "Directeur Technique / Chef de Mission",
        "about.role_ops": "Gérant Adjoint (Opérations)",
        "about.role_prog": "Gérant Adjoint (Programmes)",
        "about.bio_robert": "Expert international en S&E (ex-UN OCHA, PACT, Mercy Corps). Master en Leadership & Entrepreneuriat (Portland State Univ). Plus de 100 évaluations de projets d'urgence.",
        "about.bio_richard": "Statisticien économiste (ENSEA Abidjan / ISSNT) et expert IT. Spécialiste MEAL pour ENABEL, OIM et GIZ. Expert en gestion de bases de données complexes.",
        "about.consultants_label": "CORPS DE CONSULTANTS",
        "about.consultants_title": "<span class='color-noir'>Nos Experts</span> <span class='color-rouge'>Associés</span>",
        "about.role_meal": "Expert Senior MEAL",
        "about.role_wash": "Spécialiste WASH & Infrastructure",
        "about.role_protection": "Consultante Protection & Genre",
        "about.bio_meal": "Expert en systèmes de suivi-évaluation et data-analytics pour les grands comptes humanitaires.",
        "about.bio_wash": "Ingénieur expert en accès à l'eau et hygiène en milieux ruraux et zones de conflits.",
        "about.bio_protection": "Spécialiste de la protection de l'enfance et de l'intégration de l'approche genre.",

        "about.sector_health": "Santé Publique",
        "about.sector_mining": "Gouvernance Minière",
        "about.sector_wash": "EHA / WASH",
        "about.sector_protection": "Protection & Genre",
        "about.sector_data": "Data Analytics",
        "about.sector_eval": "Études & Évaluations",

        "services.banner_title": "Offre Stratégique & Technique",
        "services.banner_giant_elite": "<span class='color-noir'>DES SOLUTIONS ANALYTIQUES</span> <span class='color-rouge'>AU SERVICE DE L'IMPACT</span>",
        "services.banner_sub": "Vente de consultances, formations humanitaires et appui logistique en zones difficiles.",
        "services.expertise_label": "Notre Compétences",
        "services.expertise_title_part1": "<span class='color-noir'>Une expertise</span>",
        "services.expertise_title_part2": "<span class='color-rouge'>pluridisciplinaire</span>",
        "services.banner_giant1": "EPHOD",
        "services.banner_giant2": "CONSULTING",
        "services.banner_desc": "<strong style='font-size: 2.2em; display: inline-block; letter-spacing: 2px; text-transform: uppercase; font-weight: 800; text-align: center; width: 100%; background: linear-gradient(to right, #ffffff, #b01a47, #ffffff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; filter: drop-shadow(0 2px 4px rgba(0,0,0,0.3));'>Des Solutions Analytiques au Service de l'Impact</strong>",
        "portfolio.banner_title": "<span class='color-noir'>NOTRE CAPITAL</span> <span class='color-rouge'>D'IMPACT</span>",
        "ongoing.banner_title": "<span class='color-noir'>MISSIONS EN COURS</span> <span class='color-rouge'>DE RÉALISATION</span>",

        "srv.s1_title": "ÉTUDES & RECHERCHES",
        "srv.s1_desc": "Baseline, Market Study, évaluations de besoins (ERM) et diagnostics institutionnels complets.",
        "srv.s2_title": "EVALUATIONS INDÉPENDANTES",
        "srv.s2_desc": "Évaluations à mi-parcours et finales selon les critères OCDE-CAD et CHS Alliance.",
        "srv.s3_title": "SERVICES MONÉTAIRES SÉCURISÉS",
        "srv.s3_desc": "Appui aux interventions Cash (Mobile Money, Cash Express, Rémittences) en zones à accès complexe.",
        "srv.s4_title": "FORMATIONS & CAPACITATION",
        "srv.s4_desc": "Renforcement des capacités en MEAL, gestion de projet et outils de collecte (KoboToolbox/ODK).",
        "srv.s5_title": "LOGISTIQUE DE TERRAIN",
        "srv.s5_desc": "Appui à la livraison de biens et services dans les zones géographiques difficiles et fragiles.",
        "srv.s6_title": "INTÉGRATION TRANSVERSALE",
        "srv.s6_desc": "Analyses Genre, Protection, Inclusion (AAP) et Études de sensibilité aux conflits.",
        "srv.s7_title": "SERVICES CASH SÉCURISÉS",
        "srv.s7_desc": "Appui aux interventions en cash (Mobile Money, Remittances) et études de marché en zones difficiles.",
        "srv.s8_title": "LOGISTIQUE DE TERRAIN",
        "srv.s8_desc": "Support au dernier kilomètre, cartographie SIG et collecte digitalisée en contextes fragiles et d'urgence.",
        "srv.s9_title": "GENRE, PROTECTION & AAP",
        "srv.s9_title": "GENRE, PROTECTION & AAP",
        "srv.s9_desc": "Analyses transversales Genre, Protection, Inclusion et Sensibilité aux conflits intégrées dans chaque mission.",

        "services.btn_more": "EN SAVOIR PLUS <i class='bi bi-arrow-right ms-2'></i>",
        "home.method_desc2": "Nos interventions sont structurées selon les référentiels mondiaux les plus exigeants pour garantir l'efficacité, la transparence et la redevabilité de chaque mission.",
        "services.oecd_badge": "RÉFÉRENTIEL MAJEUR",
        "services.oecd_title": "CRITÈRES OCDE-CAD",
        "services.oecd_desc": "La pierre angulaire de l'évaluation du développement. Nous intégrons les 5 piliers fondamentaux dans chaque rapport :",
        "services.oecd_p1": "Pertinence",
        "services.oecd_p2": "Efficacité",
        "services.oecd_p3": "Efficience",
        "services.oecd_p4": "Impact",
        "services.oecd_p5": "Durabilité",

        "services.chs_badge": "STANDARD HUMANITAIRE",
        "services.chs_title": "CHS ALLIANCE",
        "services.chs_desc": "Notre engagement inconditionnel pour une aide redevable et centrée sur la dignité des populations affectées :",
        "services.chs_p1": "Engagement Zéro Tolérance (PSEA)",
        "services.chs_p2": "Mécanismes de redevabilité (AAP)",
        "services.chs_p3": "Apprentissage continu & Amélioration",

        "srv.modal_need": "Besoin du Client",
        "srv.modal_how": "Notre Méthodologie",
        "srv.modal_value": "Valeur Ajoutée",

        "srv.s1_need": "Nécessité de disposer de données probantes et fiables pour orienter les interventions humanitaires et de développement.",
        "srv.s1_how": "Déploiement d'enquêtes terrain (MSNA, Baseline) via outils digitaux (Kobo) et analyse statistique rigoureuse.",
        "srv.s1_value": "Une base décisionnelle solide pour maximiser l'efficacité des financements et le ciblage des bénéficiaires.",

        "srv.s2_need": "Besoin d'une vision externe neutre et de haut niveau pour valider l'impact des programmes.",
        "srv.s2_how": "Évaluations à mi-parcours et finales fondées sur les critères OCDE-CAD : pertinence, efficacité, impact.",
        "srv.s2_value": "Recommandations stratégiques actionnables pour l'amélioration continue des cycles de projet.",

        "srv.s3_need": "Sécurisation des transferts monétaires dans les zones reculées ou enclavées.",
        "srv.s3_how": "Réseau d'agents locaux et solutions mobiles (Mobile Money) adaptées aux contextes de fragilité sécuritaire.",
        "srv.s3_value": "Garantie de livraison de l'aide financière aux populations les plus vulnérables en toute sécurité.",

        "srv.s4_need": "Renforcement des compétences locales pour assurer la pérennité des acquis des projets.",
        "srv.s4_how": "Formations sur-mesure en gestion de projet, MEAL et standards de protection (PSEA/AAP).",
        "srv.s4_value": "Autonomisation des partenaires locaux et conformité aux standards internationaux (CHS).",

        "srv.s5_need": "Appui opérationnel pour la logistique du dernier kilomètre dans les zones géographiques difficiles.",
        "srv.s5_how": "Gestion de la chaîne d'approvisionnement et déploiement agile d'équipes mobiles.",
        "srv.s5_value": "Réduction des délais d'intervention et maîtrise des coûts logistiques en milieu complexe.",

        "srv.s6_need": "Intégration systématique des enjeux de genre et de protection dans toutes les phases du projet.",
        "srv.s6_how": "Analyses de vulnérabilité, études de sensibilité aux conflits et audits d'inclusion.",
        "srv.s6_value": "Réduction des risques de protection et promotion de la dignité et de l'équité des bénéficiaires.",

        "portfolio.banner_title": "<span class='color-noir'>NOTRE CAPITAL</span> <span class='color-rouge'>D'IMPACT</span>",
        "portfolio.banner_sub": "Plus d'une décennie d'expertise opérationnelle au service des partenaires humanitaires et du développement.",
        "port.all": "Toutes",
        "port.cat1": "Études & Évaluations",
        "port.cat2": "Conseil & Stratégie",
        "port.cat3": "Logistique & Cash",
        "port.more": "Détails de la mission",
        "port.modal_download": "Fiche Projet",
        "port.modal_challenge": "Le Défi",
        "port.modal_strategy": "La Stratégie",
        "port.modal_impact_title": "L'Impact",

        "port.p1_title": "Étude Marché & Risques Cash", "port.p1_client": "Jesuite Refugee Service (JRS)", "port.p1_zone": "Kayna & Lubero (Nord-Kivu)", "port.p1_date": "Mars – Avril 2026", "port.p1_context": "Étude du marché et évaluation des risques de protection pour les interventions cash. Analyse genre et sensibilité aux conflits.", "port.p1_solution": "Enquêtes terrain et cartographie des risques financiers.", "port.p1_impact": "Optimisation des transferts cash pour JRS. Contact: Vincent KISHALI (vincent.kishali@jrs.net)",
        "port.p2_title": "Identification Parties Prenantes", "port.p2_client": "ULB", "port.p2_zone": "Karisimbi & Nyiragongo (Goma)", "port.p2_date": "Juin – Juillet 2024", "port.p2_context": "Identification des OAC dans les aires de santé du Nord-Kivu pour le compte de l'ULB.", "port.p2_solution": "Analyse systémique des acteurs de santé locaux.", "port.p2_impact": "Cartographie opérationnelle validée. Contact: Billy MWANGAZA (mwangazabilly@gmail.com)",
        "port.p3_title": "Réponse Multisectorielle Intégrée", "port.p3_client": "Umoja in Action", "port.p3_zone": "Walikale & Bunyakiri", "port.p3_date": "Mars – Avril 2026", "port.p3_context": "Étude de base et analyse des risques de protection pour un projet Cash, Éducation et Sécurité Alimentaire.", "port.p3_solution": "Méthodologie MSNA et analyse de sensibilité aux conflits.", "port.p3_impact": "Base décisionnelle robuste pour Umoja. Contact: Fiston MALIBA (filston.maliba@umojainaction.org)",
        "port.p4_title": "Enquête PDM & Satisfaction", "port.p4_client": "Christian Aid", "port.p4_zone": "Z.S. de KALEHE (Sud-Kivu)", "port.p4_date": "Février – Mars 2026", "port.p4_context": "Réalisation d'une enquête Post Distribution Monitoring (PDM) pour évaluer la satisfaction des bénéficiaires.", "port.p4_solution": "Enquêtes directes et mécanismes de redevabilité (AAP).", "port.p4_impact": "Amélioration de la qualité de l'aide Christian Aid. Contact: Obed BUHENDWA (OBuhendwa@christian-aid.org)",
        "port.p5_title": "Formation Gestion Programmatique", "port.p5_client": "RACOJ Nord-Kivu", "port.p5_zone": "Goma (Nord-Kivu)", "port.p5_date": "Mars 2026", "port.p5_context": "Facilitation de la formation sur la gestion programmatique de projet pour les PHPs du programme Together 2.0.", "port.p5_solution": "Modules techniques sur le cycle de projet et les standards CHS.", "port.p5_impact": "Capacitation renforcée du RACOJ. Contact: Juste YAMONEKA (justewasso@gmail.com)",
        "port.p6_title": "Évaluation Rapide Multisectorielle", "port.p6_client": "GHOVODI & ODH", "port.p6_zone": "Uvira & RUZIZI (Sud-Kivu)", "port.p6_date": "Janvier 2026", "port.p6_context": "ERM, Étude de marché et analyse de sensibilité aux conflits dans les zones d'Uvira.", "port.p6_solution": "Évaluations rapides de terrain et focus groupes.", "port.p6_impact": "Planification de réponse d'urgence validée. Contact: Emmanuel KAZIGE (kazige20@gmail.com)",
        "port.p7_title": "Évaluation Rapide Walikale/Oicha", "port.p7_client": "GHOVODI & ODH", "port.p7_zone": "Walikale, Oicha, Kayna", "port.p7_date": "Nov – Déc 2025", "port.p7_context": "Évaluation rapide multisectorielle des besoins (ERM) dans les zones d'accès complexe.", "port.p7_solution": "Déploiement agile d'enquêteurs et analyse multisectorielle.", "port.p7_impact": "Ciblage humanitaire précis. Contact: Félicien KITOKO (odhasbl@gmail.com)",
        "port.p8_title": "Éval Mi-parcours Malnutrition", "port.p8_client": "RACOJ (DKH)", "port.p8_zone": "Demba (Kasaï Central)", "port.p8_date": "Décembre 2024", "port.p8_context": "Évaluation à mi-parcours du projet d'appui aux moyens de subsistance pour la lutte contre la malnutrition.", "port.p8_solution": "Évaluation qualitative et quantitative des indicateurs nutritionnels.", "port.p8_impact": "Réorientation stratégique du projet RACOJ. Contact: Juste YAMONEKA (justewasso@gmail.com)",
        "port.p9_title": "Sondage Médias M4D", "port.p9_client": "La Benevolencija", "port.p9_zone": "Rutshuru, Lubero, Masisi", "port.p9_date": "Septembre 2023", "port.p9_context": "Sondage des médias pour le projet Media for Development (M4D) dans le Grand Nord.", "port.p9_solution": "Enquêtes d'audience et analyse de perception communautaire.", "port.p9_impact": "Optimisation de la stratégie de communication M4D. Contact: Nelson BENEVOLENCIA",
        "port.p10_title": "Évaluation Finale Éducation", "port.p10_client": "ODH", "port.p10_zone": "FIZI (Sud-Kivu)", "port.p10_date": "Août 2024", "port.p10_context": "Évaluation finale du projet d'assistance multisectorielle intégrée en éducation et protection de l'enfant.", "port.p10_solution": "Audit de performance selon les critères OCDE-CAD.", "port.p10_impact": "Validation des acquis éducatifs à Fizi. Contact: Félicien KITOKO (odhasbl@gmail.com)",
        "port.p11_title": "Éval Malnutrition Demba", "port.p11_client": "RACOJ NK (DKH)", "port.p11_zone": "ZS de DEMBA (Kasaï Central)", "port.p11_date": "Septembre 2022", "port.p11_context": "Réduction de la prévalence de la malnutrition dans la zone de Demba.", "port.p11_solution": "Évaluation mi-parcours des systèmes de santé locaux.", "port.p11_impact": "Impact nutritionnel mesuré en zone rurale. Contact: Juste YAMONEKA (justewasso@gmail.com)",
        "port.p12_title": "Éval Production Agricole", "port.p12_client": "RACOJ NK (DKH)", "port.p12_zone": "DEMBA (Kasaï Central)", "port.p12_date": "Juillet 2023", "port.p12_context": "Évaluation du projet de réduction des effets de la crise alimentaire par la production agricole.", "port.p12_solution": "Analyse des rendements et de la résilience communautaire.", "port.p12_impact": "Sécurité alimentaire renforcée. Contact: Juste YAMONEKA (justewasso@gmail.com)",
        "port.p13_title": "Analyse Systèmes de Marché", "port.p13_client": "UNHCR", "port.p13_zone": "Ubangi & Bas-Uele", "port.p13_date": "Mars 2024", "port.p13_context": "Évaluation des systèmes de marché et chaînes de valeur pour les réfugiés centrafricains.", "port.p13_solution": "Études de marché et cartographie des chaînes d'approvisionnement.", "port.p13_impact": "Autonomisation économique des réfugiés. Contact: Jean Serge BASHONGA (bashonga@unhcr.org)",
        "port.p14_title": "Évaluation UKWELI BILA CHUKI", "port.p14_client": "La Benevolencija", "port.p14_zone": "Nord-Kivu", "port.p14_date": "Juin 2024", "port.p14_context": "Rapport d'évaluation finale du projet de cohésion sociale et lutte contre la désinformation.", "port.p14_solution": "Analyse de sensibilité aux conflits et d'impact social.", "port.p14_impact": "Cohésion sociale renforcée. Contact: Nelson BENEVOLENCIA",
        "port.p15_title": "Évaluation Besoins ERM", "port.p15_client": "SCI, MEDAIR, CARE, IMC", "port.p15_zone": "Ituri, Nord & Sud Kivu", "port.p15_date": "Octobre 2023", "port.p15_context": "Consultant principal pour mener l'ERM du consortium humanitaire majeur.", "port.p15_solution": "Coordination de collecte de données multisectorielle rapide.", "port.p15_impact": "Réponse rapide du consortium validée. Contact: Alex FIKIRI (Alex.Fikiri@savethechildren.org)",
        "port.p16_title": "Éval Finale Éducation Urgence", "port.p16_client": "UNICEF / SCI", "port.p16_zone": "8 Provinces de la RDC", "port.p16_date": "Février – Mars 2023", "port.p16_context": "Évaluation finale des projets d'éducation en situations d'urgence (8 provinces).", "port.p16_solution": "Audit technique et qualitatif de l'accès à l'éducation.", "port.p16_impact": "Recommandations pour l'éducation en zone de conflit. Contact: Alex FIKIRI",
        "port.p17_title": "Éval Éducation COVID-19", "port.p17_client": "UNICEF / SCI", "port.p17_zone": "Toute la RDC (16 prov.)", "port.p17_date": "Mars 2022", "port.p17_context": "Évaluation finale du projet d'éducation à distance pendant la pandémie.", "port.p17_solution": "Analyse de la l'efficacité des outils de continuité pédagogique.", "port.p17_impact": "Leçons apprises pour la résilience éducative. Contact: Alex FIKIRI",
        "port.p18_title": "Étude Marché Emploi IDPs", "port.p18_client": "Jesuite Refugee Service", "port.p18_zone": "Masisi (RDC)", "port.p18_date": "Mai 2019", "port.p18_context": "Recherche sur le marché de l'emploi dans les camps de déplacés internes.", "port.p18_solution": "Diagnostic des compétences et opportunités locales.", "port.p18_impact": "Stratégie d'employabilité JRS. Contact: Vincent KISHALI (vincent.kishali@jrs.net)",
        "port.p19_title": "Éval Formation Professionnelle", "port.p19_client": "Fondation Follereau", "port.p19_zone": "Ségou (Mali)", "port.p19_date": "Septembre 2019", "port.p19_context": "Évaluation finale du projet de développement de l'employabilité des jeunes vulnérables.", "port.p19_solution": "Audit de performance et analyse de l'insertion pro.", "port.p19_impact": "Validation du modèle de formation au Mali. Contact: Clémentine GLOIRE (clementine.gloire@ffl.lu)",
        "port.p20_title": "Système S&E Programme FSP", "port.p20_client": "Mercy Corps", "port.p20_zone": "Bukavu (RDC)", "port.p20_date": "Août 2017", "port.p20_context": "Développement du système de suivi-évaluation et révision des indicateurs pour le projet FSP.", "port.p20_solution": "Conception d'outils digitaux et tableaux de bord MEAL.", "port.p20_impact": "Pilotage basé sur les résultats pour Mercy Corps. Contact: Jean DANIEL (jdaniel@cd.mercycorps.org)",

        "ongoing.page_title": "Suivi des Missions",
        "ongoing.page_subtitle": "État d'avancement de nos contrats de consultance en cours pour 2026.",
        "ongoing.progress": "Progression",
        "ongoing.proj1_title": "Mission ProGERIM II (GIZ)",
        "ongoing.proj1_desc": "Amélioration de la transparence des revenus miniers pour les ETD du Lualaba et Haut-Katanga. Collecte LQAS en cours.",
        "ongoing.proj2_title": "Evaluation JRS (Kayna/Lubero)",
        "ongoing.proj2_desc": "Analyse Genre, Inclusion et Sensibilité aux conflits. Mission de terrain Luéro engagée à 85%.",
        "ongoing.proj3_title": "Audit SONAHU (Nord-Kivu)",
        "ongoing.proj3_desc": "Audit de gouvernance et conformité OHADA pour le partenaire SONAHU.",
        "ongoing.proj4_title": "Umoja in Action (MEAL)",
        "ongoing.proj4_desc": "Appui au système de suivi-évaluation pour la réponse multisectorielle à Walikale.",

        "careers.banner_title": "<span class='color-noir'>OFFRES</span> <span class='color-rouge'>D'EMPLOI</span>",
        "careers.banner_sub": "EPHOD recrute des profils d'experts bilingues pour ses missions de recherche et formation.",
        "careers.job1_title": "Consultants Seniors",
        "careers.job1_desc": "Experts en planification stratégique et évaluations OCDE. Maîtrise des standards CHS requise.",
        "careers.policy_label": "Gouvernance & Éthique",
        "careers.policy_title": "<span class='color-noir'>Notre Politique</span> <span class='color-rouge'>Ressources Humaines</span>",
        "careers.p_legal_title": "Engagement Légal",
        "careers.policy_legal": "La gestion RH d'EPHOD Consulting est strictement régie par le droit OHADA et le Code du Travail de la RDC. Nous garantissons une protection sociale complète et un environnement de travail sécurisé.",
        "careers.p_equity_title": "Équité & Diversité",
        "careers.policy_equity": "Le recrutement repose sur la transparence, l’égalité des chances et la non-discrimination. Chaque talent est évalué uniquement sur ses compétences techniques et son adhésion à nos valeurs d'excellence.",
        "careers.apply": "Envoyer Candidature",

        "contact.banner_eyebrow": "CONTACT & ADRESSES",
        "contact.banner_title": "<span class='color-noir'>Présence</span> <span class='color-rouge'>Nationale</span>",
        "contact.banner_sub": "Siège à Kinshasa et antennes techniques à Goma et Beni.",
        "contact.label_offices": "Nos Bureaux",
        "contact.offices_title": "<span class='color-noir'>Où nous</span> <span class='color-rouge'>Trouver ?</span>",
        "contact.addr_kin_label": "Kinshasa (Siège)",
        "contact.addr_kin_text": "Q. Ma Campagne, Av. Kapaya N°03,<br>Commune de Ngaliema",
        "contact.addr_goma_label": "Goma (Antenne)",
        "contact.addr_goma_text": "Q. Kyeshero, Av. Kituku N°13",
        "contact.addr_beni_label": "Beni (Antenne)",
        "contact.addr_beni_text": "RN4, Av. Opienge N°6",
        "contact.kin_tab": "KINSHASA (SIÈGE)",
        "contact.goma_tab": "GOMA",
        "contact.beni_tab": "BENI",
        "contact.map_tag_kin": "NOTRE SIÈGE — KINSHASA",
        "contact.map_tag_goma": "ANTENNE — GOMA",
        "contact.map_tag_beni": "ANTENNE — BENI",
        "contact.fast_contacts_title": "Contacts Rapides",
        "contact.form_title": "<span class='color-noir'>Envoyez-nous</span> <span class='color-rouge'>un Message</span>",
        "contact.form_name": "Nom Complet",
        "contact.form_email": "Email",
        "contact.form_msg": "Votre message",
        "contact.form_send": "Envoyer",
        "contact.map_tag": "NOTRE SIÈGE — KINSHASA",

        "footer.contact_title": "Contact",
        "footer.desc": "Cabinet d'expertise humanitaire et de développement (RCCM CD/KNG/RCCM/25-B-03958).",
        "footer.rights": "Tous droits réservés.",
        "footer.made": "EPHOD CONSULTING SARL",
        "footer.addr_kin": "Kinshasa: Q. Ma Campagne, Av. Kapaya N°03, C/Ngaliema",
        "footer.addr_goma": "Goma: Q. Kyeshero, Av. Kituku N°13",
        "footer.addr_beni": "Beni: RN4, Face ENERA, Entrée KVG, N°6",

        "about.rccm": "RCCM: CD/KNG/RCCM/25-B-03958",
        "about.idnat": "ID NAT: 01-H5300-N88322C",
        "about.ungm": "UNGM: 1175536",
        "about.nif": "NIF: A2559012X",
        "about.bank_title": "Coordonnées Bancaires",
        "about.bank_acc": "Compte USD: 00011-15066-62002620265-77",
        "about.bank_swift": "Swift: BCDCCDKIxxx",

        "about.pillar1_title": "Bâtir",
        "about.pillar1_desc": "La résilience des organisations face aux contextes complexes.",
        "about.pillar2_title": "Catalyser",
        "about.pillar2_desc": "Une performance opérationnelle de standard international.",
        "about.pillar3_title": "Transformer",
        "about.pillar3_desc": "Vos ambitions stratégiques en impacts concrets et pérennes.",
        
        "about.role_dg_desc": "Visionnaire et garante de l'excellence stratégique d'EPHOD Consulting.",
        "about.role_ops_desc": "Expert en coordination et déploiements terrain en environnements complexes.",

        "careers.p_dev_title": "Développement Continu",
        "careers.policy_dev": "Formations régulières, mentorat par des experts seniors et opportunités de croissance au sein de missions à forte valeur ajoutée dans toute la RDC.",
        
        "careers.jobs_label": "POSTES OUVERTS",
        "careers.jobs_title": "Opportunités <span>Actuelles</span>",
        "careers.job1_title": "Consultants & Experts Indépendants",
        "careers.job1_desc": "Réseau d'experts internationaux spécialisés (Santé, Éducation, Protection, WASH, MEAL). Connaissance ISO/CHS recommandée.",
        "careers.job1_req1": "Master minimum en sciences sociales, santé publique ou équivalent",
        "careers.job1_req2": "5+ ans d'expérience en contexte humanitaire",
        "careers.job1_req3": "Maîtrise de KoboToolbox, SPSS ou Stata",
        "careers.job1_req4": "Excellente capacité rédactionnelle (rapports & proposals)",
        
        "careers.job2_title": "Techniciens de Recherche",
        "careers.job2_desc": "Chargés de la collecte (KoboToolbox) et rédaction de proposals/rapports. Bilinguisme obligatoire.",
        "careers.job2_req1": "Licence en statistiques, économie ou sciences sociales",
        "careers.job2_req2": "Expérience en collecte de données digitalisée",
        "careers.job2_req3": "Capacité à travailler en zones d'accès complexe",
        "careers.job2_req4": "Connaissance des protocoles LQAS/MSNA appréciée",
        
        "careers.job_req_title": "Profil recherché :",
        "careers.job_apply_btn": "Postuler maintenant",

        "careers.form_label": "CANDIDATURE",
        "careers.form_title": "Rejoignez <span>l'Excellence</span>",
        "careers.form_sub": "Soumettez votre candidature complète. Notre équipe RH analysera votre profil sous 72h ouvrables.",
        "careers.lbl_name": "Nom complet *",
        "careers.ph_name": "Ex: Jean-Pierre KASONGO",
        "careers.lbl_email": "Adresse email *",
        "careers.lbl_phone": "Téléphone *",
        "careers.lbl_pos": "Poste visé *",
        "careers.opt_def": "— Sélectionnez un poste —",
        "careers.opt_1": "Consultant & Expert Indépendant",
        "careers.opt_2": "Technicien de Recherche",
        "careers.opt_3": "Candidature spontanée",
        "careers.lbl_cv": "Curriculum Vitae (PDF uniquement) *",
        "careers.cv_drop": "Glissez votre CV ici ou <strong>cliquez pour parcourir</strong>",
        "careers.cv_format": "Format PDF — Max 5 Mo",
        "careers.lbl_letter": "Lettre de motivation *",
        "careers.ph_letter": "Décrivez votre motivation, vos compétences clés et votre disponibilité...",
        "careers.lbl_lk": "Profil LinkedIn (optionnel)",
        "careers.lbl_avail": "Disponibilité",
        "careers.avail_1": "Immédiate",
        "careers.avail_2": "Sous 1 mois",
        "careers.avail_3": "Sous 3 mois",
        "careers.avail_4": "À négocier",
        "careers.btn_submit": "Soumettre ma candidature",
        "careers.form_disc": "En soumettant ce formulaire, vous acceptez que vos données soient traitées conformément à notre politique de confidentialité.",

        "ongoing.banner_title": "<span class='color-noir'>MISSIONS</span> <span class='color-rouge'>EN COURS DE RÉALISATION</span>",
        "ongoing.ticker_label": "LIVE LOG",
        "ongoing.tick1": "Mission ProGERIM : Phase de collecte LQAS finalisée dans 3 ETD du Lualaba...",
        "ongoing.tick2": "Mission JRS : Équipe d'évaluation déployée à Kayna et Lubero...",
        "ongoing.tick3": "Audit SONAHU : Revue de conformité OHADA engagée à 40%...",
        "ongoing.tick4": "Umoja in Action : Système MEAL configuré sur KoboToolbox...",
        "ongoing.tick5": "Logistique EPHOD : Convoi technique arrivé à Beni...",

        "ongoing.badge_action": "ACTION EN COURS",
        "ongoing.proj1_title": "Mission ProGERIM II (GIZ)",
        "ongoing.proj1_desc": "Amélioration de la transparence des revenus miniers pour les ETD du Lualaba et Haut-Katanga. Collecte LQAS en cours.",
        "ongoing.p1_meta1": "Lualaba & Haut-Katanga",
        "ongoing.p1_meta2": "GIZ / ProGERIM",

        "ongoing.badge_terrain": "MISSION TERRAIN",
        "ongoing.proj2_title": "Evaluation JRS (Kayna/Lubero)",
        "ongoing.proj2_desc": "Analyse Genre, Inclusion et Sensibilité aux conflits. Mission de terrain Lubero engagée à 85%.",
        "ongoing.p2_meta1": "Nord-Kivu (Lubero)",
        "ongoing.p2_meta2": "JRS RD CONGO",

        "ongoing.badge_audit": "AUDIT EPHOD",
        "ongoing.proj3_title": "Audit SONAHU (Nord-Kivu)",
        "ongoing.proj3_desc": "Audit de gouvernance et conformité OHADA pour le partenaire SONAHU.",
        "ongoing.p3_meta1": "Nord-Kivu",
        "ongoing.p3_meta2": "SONAHU A.S.B.L",

        "ongoing.badge_support": "SUPPORT MEAL",
        "ongoing.proj4_title": "Umoja in Action (MEAL)",
        "ongoing.proj4_desc": "Appui au système de suivi-évaluation pour la réponse multisectorielle à Walikale.",
        "ongoing.p4_meta1": "Walikale Territory",
        "ongoing.p4_meta2": "Umoja in Action",

        "ongoing.progress": "Progression Opérationnelle",

        "ongoing.kpi1": "Missions Actives",
        "ongoing.kpi2": "Experts Déployés",
        "ongoing.kpi3": "Provinces Couvertes",
        "ongoing.kpi4": "Satisfaction Partenaire",

        "footer.nav_title": "NAVIGATION",
        "footer.offices_title": "BUREAUX & CONTACT",
        "footer.kin_label": "KINSHASA (SIÈGE)",
        "footer.goma_label": "GOMA",
        "footer.beni_label": "BENI",
        "footer.direct_label": "CONTACT DIRECT",
        "srv_m1.title": "ÉTUDES & RECHERCHES",
        "srv_m1.subtitle": "NOTRE EXPERTISE ANALYTIQUE",
        "srv_m1.intro": "EPHOD Consulting déploie des méthodologies rigoureuses pour éclairer la prise de décision stratégique :",
        "srv_m1.i1_title": "Baseline & Endline Surveys :",
        "srv_m1.i1_desc": "Établissement de situations de référence et mesure finale des indicateurs.",
        "srv_m1.i2_title": "Études de Marché & Faisabilité :",
        "srv_m1.i2_desc": "Analyse de l'offre, de la demande et des chaînes de valeur locales.",
        "srv_m1.i3_title": "Diagnostics Institutionnels :",
        "srv_m1.i3_desc": "Audit des capacités organisationnelles et opérationnelles.",
        "srv_m1.i4_title": "Analyses Sectorielles :",
        "srv_m1.i4_desc": "Santé Publique, Mines, Agriculture et EHA (WASH).",
        "srv_m2.title": "ÉVALUATIONS INDÉPENDANTES",
        "srv_m2.subtitle": "REDEVABILITÉ & PERFORMANCE",
        "srv_m2.intro": "Nous évaluons l'impact de vos programmes selon les plus hauts standards internationaux :",
        "srv_m2.i1_title": "Critères OCDE-CAD :",
        "srv_m2.i1_desc": "Analyse de pertinence, efficacité, efficience, impact et durabilité.",
        "srv_m2.i2_title": "Evaluations Real-Time :",
        "srv_m2.i2_desc": "Ajustements techniques en cours d'exécution pour optimiser l'impact.",
        "srv_m2.i3_title": "Audit de Qualité (CHS) :",
        "srv_m2.i3_desc": "Vérification de la conformité aux standards Humanitaires Fondamentaux.",
        "srv_m3.title": "SERVICES MONÉTAIRES",
        "srv_m3.subtitle": "SOLUTIONS CASH AGILES",
        "srv_m3.intro": "EPHOD facilite les transferts monétaires sécurisés dans les zones à haut risque :",
        "srv_m3.i1_title": "Mobile Money Displacement :",
        "srv_m3.i1_desc": "Gestion des flux via les opérateurs locaux en zones fragiles.",
        "srv_m3.i2_title": "Vérification PDM (Post Distribution Monitoring) :",
        "srv_m3.i2_desc": "Suivi de l'utilisation des fonds par les bénéficiaires.",
        "srv_m3.i3_title": "Vendor Mapping :",
        "srv_m3.i3_desc": "Identification et contractualisation de commerçants locaux.",
        "srv_m4.title": "FORMATIONS & CAPACITATION",
        "srv_m4.subtitle": "DÉVELOPPEMENT DES COMPÉTENCES",
        "srv_m4.intro": "Renforcement des capacités de vos équipes terrain et partenaires locaux :",
        "srv_m4.i1_title": "Cycle de Projet & MEAL :",
        "srv_m4.i1_desc": "Conception de cadres logiques et de systèmes de suivi-évaluation.",
        "srv_m4.i2_title": "Digital Data Collection :",
        "srv_m4.i2_desc": "Formation avancée sur KoboToolbox, ODK et PowerBI.",
        "srv_m4.i3_title": "Gouvernance & Management :",
        "srv_m4.i3_desc": "Leadership humanitaire et management en contextes de crise.",
        "srv_m5.title": "LOGISTIQUE DE TERRAIN",
        "srv_m5.subtitle": "SUPPORT OPÉRATIONNEL",
        "srv_m5.intro": "Optimisation de votre chaîne d'approvisionnement en milieux hostiles :",
        "srv_m5.i1_title": "Last-Mile Delivery :",
        "srv_m5.i1_desc": "Acheminement de biens critiques (médicaments, intrants) vers les zones isolées.",
        "srv_m5.i2_title": "Gestion d'entrepôts :",
        "srv_m5.i2_desc": "Stockage et inventaire assisté par outils numériques.",
        "srv_m5.i3_title": "Support au Déploiement :",
        "srv_m5.i3_desc": "Mise en place rapide de bases de vie et de bureaux mobiles.",
        "srv_m6.title": "INTÉGRATION TRANSVERSALE",
        "srv_m6.subtitle": "ÉQUITÉ & SENSIBILITÉ",
        "srv_m6.intro": "Veiller à l'inclusion et à la dignité dans toutes les phases du projet :",
        "srv_m6.i1_title": "Analyse de Genre & Inclusion :",
        "srv_m6.i1_desc": "Intégration des besoins spécifiques des femmes, enfants et personnes handicapées.",
        "srv_m6.i2_title": "Sensibilité aux Conflits :",
        "srv_m6.i2_desc": "Approche 'Do No Harm' pour éviter d'exacerber les tensions locales.",
        "srv_m6.i3_title": "Redevabilité (AAP) :",
        "srv_m6.i3_desc": "Mise en place de mécanismes de plainte et de feedback des bénéficiaires."
    },
    en: {
        "nav.home": "Home",
        "nav.about": "About Us",
        "nav.services": "Services",
        "nav.portfolio": "Works",
        "nav.ongoing": "Ongoing",
        "nav.careers": "Careers",
        "nav.logo": "EPHOD Consulting",
        
        "nav.drop_vision": "Our Vision",
        "nav.drop_vision_sub": "Values & Identity",
        "nav.drop_team": "Our Team",
        "nav.drop_team_sub": "Dedicated Experts",
        "nav.drop_strat_short": "Strategic Advisory",
        "nav.drop_strat_sub2": "Governance & M&E",
        "nav.drop_digital_short": "Digital & GIS",
        "nav.drop_digital_sub2": "Data Innovation",
        "nav.drop_public_short": "Studies & Evaluations",
        "nav.drop_public_sub2": "OECD-DAC Standards",
        
        "menu.home_head": "Header",
        "menu.home_head_sub": "Back to top",
        "menu.home_news": "Latest Missions",
        "menu.home_news_sub": "Our recent updates",
        "menu.home_partners": "Trusted Network",
        "menu.home_partners_sub": "Our collaborators",
        
        "menu.about_vision": "Our Vision",
        "menu.about_vision_sub": "Values & identity",
        "menu.about_mission": "Our Mission",
        "menu.about_mission_sub": "EPHOD commitments",
        "menu.about_team": "Our Team",
        "menu.about_team_sub": "Multidisciplinary experts",
        
        "menu.srv_audit": "Audit & Assurance",
        "menu.srv_audit_sub": "Comprehensive expertise",
        "menu.srv_cap": "Capacity Building",
        "menu.srv_cap_sub": "Training & coaching",
        "menu.srv_support": "Management Support",
        "menu.srv_support_sub": "Project accompaniment",
        "menu.srv_eval": "Strategic Evaluations",
        "menu.srv_eval_sub": "Impact measurement",
        
        "menu.port_lualaba": "Lualaba & Haut-Katanga",
        "menu.port_lualaba_sub": "Mining sector",
        "menu.port_kivu": "North Kivu",
        "menu.port_kivu_sub": "Risk & Protection",
        "menu.port_sud": "South Kivu",
        "menu.port_sud_sub": "PDM Evaluations",
        
        "menu.ong_missions": "Current Missions",
        "menu.ong_missions_sub": "In the field",
        "menu.ong_zones": "Complex Access Zones",
        "menu.ong_zones_sub": "DRC deployments",
        
        "menu.car_join": "Join the Team",
        "menu.car_join_sub": "EPHOD opportunities",
        "menu.car_network": "Expert Network",
        "menu.car_network_sub": "Independent consultants",
        
        "menu.contact_offices": "Our Offices",
        "menu.contact_offices_sub": "Kinshasa, Goma, Beni",
        "menu.contact_write": "Write to us",
        "menu.contact_write_sub": "Requests & Support",
        
        "hero.eyebrow": "CONSULTING • INNOVATION • IMPACT",
        "hero.line0": "EPHOD CONSULTING",
        "hero.line1": "STRENGTHENING conditions for",
        "hero.line2": "SUSTAINABLE DEVELOPMENT.",
        "hero.line3": "MEASURING impact to",
        "hero.line4": "IMPROVE practices.",
        "hero.subtitle": "A consulting firm committed to creating measurable social and economic impact in emerging countries.",
        "hero.scroll": "Discover",
        "hero.next": "See Impact",

        "home.services_label": "OUR DOMAINS",
        "home.services_title": "Contextualized <span>Approach</span>",
        "home.hero_srv_title": "High-Level <span>Expertise</span>",
        "home.stat1_label": "Successful Missions",
        "home.stat2_label": "Associate Experts",
        "home.stat3_label": "Provinces Covered",
        "home.stat4_label": "% Satisfaction",
        "home.method_label": "Rigor & Quality",
        "home.method_title": "<span class='color-noir'>International</span> <span class='color-rouge'>Standards</span>",
        "home.method_title_part1": "International",
        "home.method_title_part2": "Standards",
        "home.method_desc": "Our interventions are guided by OECD-DAC evaluation criteria and CHS Alliance standards.",
        "home.m1_title": "OECD-DAC",
        "home.m1_desc": "Relevance, effectiveness, efficiency, impact, and sustainability at the core of our studies.",
        "home.m2_title": "CHS ALLIANCE",
        "home.m2_desc": "Formal commitment to accountability and protection against abuse (PSEA).",
        "home.about_desc": "EPHOD Consulting SARL — Congolese firm specializing in independent evaluation, strategic support and capacity building (OECD-DAC, CHS).",
        "home.intro_label": "INSTITUTIONAL PROFILE",
        "home.acronym_tag": "EPHOD =",
        "home.acronym_meaning": "<span class='color-noir'>Expertise in Humanitarian Planning</span> <span class='color-rouge'>and Operationalization of Development</span>",
        "home.intro_quote": "\"Methodological rigor at the service of poverty reduction.\"",
        "home.intro_title_black": "Strategic expertise &",
        "home.intro_title_red": "independent analysis",
        "home.intro_btn": "+ READ MORE",
        "home.services_heading": "<span class='color-noir'>WHAT WE DO</span> <span class='color-rouge'>FOR YOU.</span>",
        "home.partners_label": "TRUSTED NETWORK",
        "home.partners_title": "Our Partners & Collaborators.",
        "home.partners_heading": "<span style='color: #111111;'>Our Partners &amp;</span> <span style='background: linear-gradient(90deg, #8C1338, #FF2E2E); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; display: inline-block; margin-left: 8px;'>Collaborators.</span>",
        "home.news_label": "NEWS",
        "home.news_title_line1": "DISCOVER",
        "home.news_title_line2": "OUR LATEST",
        "home.news_title_line3": "NEWS / UPDATES.",
        "home.news_title": "Latest <span>Missions</span>",
        "home.news_btn": "All our news",
        "home.news_more": "Read more",
        "home.news1_zone": "LUALABA & HAUT-KATANGA",
        "home.news1_title": "ProGERIM II — GIZ",
        "home.news1_desc": "Data collection and analysis on the proper management of sub-national mining revenues in the DRC.",
        "home.news2_zone": "NORTH KIVU — Kayna & Lubero",
        "home.news2_title": "JRS Study 2026",
        "home.news2_desc": "Market study and protection risk assessment related to cash interventions for displaced populations.",
        "home.news3_zone": "SOUTH KIVU",
        "home.news3_title": "PDM Christian Aid",
        "home.news3_desc": "Post Distribution Monitoring — evaluating the results of cash interventions in complex access areas of South Kivu.",

        "about.banner_title": "<span class='color-noir'>EXCELLENCE AT THE SERVICE</span> <span class='color-rouge'>OF IMPACT</span>",
        "about.banner_sub": "Registered firm (RCCM CD/KNG/RCCM/25-B-03958) dedicated to performance and accountability in fragile contexts.",
        "about.banner_desc": "EPHOD Consulting deploys cutting-edge expertise to transform complex challenges into sustainable impacts. Operational excellence at world standards, even in fragile contexts.",
        "about.values_title": "<span class='color-noir'>Our Core</span> <span class='color-rouge'>Values</span>",
        "about.vision_label": "Our Vision",
        "about.vision_title": "<span class='color-noir'>Analytical Independence,</span> <span class='color-rouge'>Agile Deployment</span>",
        "about.vision_p1": "EPHOD Consulting SARL stands out for its deep understanding of local dynamics and its operational capability in complex environments, from Kasai to Ituri.",
        "about.vision_p2": "We support partners (GIZ, UNICEF, UNHCR, SCI) throughout the project cycle, producing impact-oriented analysis for social and humanitarian interventions.",
        "about.motto": "Methodological rigor at the service of poverty reduction.",
        "about.val1_title": "Excellence",
        "about.val1_desc": "We maintain the highest professional standards in every mission, aligned with OECD-DAC and CHS frameworks.",
        "about.val2_title": "Independence",
        "about.val2_desc": "Our evaluations are rigorous, objective, and free from any conflict of interest, ensuring full credibility for our partners.",
        "about.val3_title": "Impact",
        "about.val3_desc": "Every intervention targets measurable and sustainable results. We design solutions tailored to local realities.",
        "about.val4_title": "Proximity",
        "about.val4_desc": "We operate right in the field, even in hard-to-reach areas, through our offices in Kinshasa, Goma, and Beni.",
        "about.role_dg_desc": "Visionary and guarantor of the strategic excellence of EPHOD Consulting.",
        "about.role_ops_desc": "Expert in coordination and field deployments in complex environments.",
        "about.network_feat4_title": "Mobility & Agility",
        "about.network_feat4_desc": "Agile operational deployment within 48h across the entire national territory.",
        "about.conformity": "Compliance Commitment",
        "about.network_label": "OUR HUMAN CAPITAL",
        "about.network_title": "<span class='color-noir'>Network of</span> <span class='color-rouge'>+50 Experts</span>",
        "about.network_desc": "Beyond our permanent team, EPHOD Consulting mobilizes a pool of high-level associate experts specialized by sector: Health, Studies, Mining Governance, WASH, and Protection.",
        "about.network_feat1": "High-level National & International Experts",
        "about.network_feat2": "Full mastery of OECD-DAC standards and the CHS Alliance",
        "about.network_feat3": "Agile deployment capacity in complex access areas",
        "about.network_count_label": "Associate Consultants",
        "about.network_availability": "Available for emergency and development missions across the entire national territory.",

        "about.team_label": "LEADERSHIP",
        "about.team_title": "<span class='color-noir'>Strategic</span> <span class='color-rouge'>Direction</span>",
        "about.role_dg": "Main Manager",
        "about.role_ops": "Deputy Manager (Operations)",
        "about.role_prog": "Deputy Manager (Programs)",
        "about.bio_richard": "Economist statistician (ENSEA Abidjan). MEAL expert for ENABEL, IOM and GIZ.",
        "about.role_wash": "WASH & Infrastructure Specialist",
        "about.role_protection": "Protection & Gender Consultant",
        "about.bio_meal": "Expert in monitoring-evaluation systems and data analytics for major humanitarian accounts.",
        "about.bio_wash": "Expert engineer in water access and hygiene in rural areas and conflict zones.",
        "about.bio_protection": "Specialist in child protection and gender-approach integration.",
        "about.consultants_label": "CONSULTING BODY",
        "about.consultants_title": "<span class='color-noir'>Our Associate</span> <span class='color-rouge'>Experts</span>",

        "about.sector_health": "Public Health",
        "about.sector_mining": "Mining Governance",
        "about.sector_wash": "WASH",
        "about.sector_protection": "Protection & Gender",
        "about.sector_data": "Data Analytics",
        "about.sector_eval": "Studies & Evaluations",

        "services.banner_title": "Strategic & Technical Offer",
        "services.banner_giant_elite": "<span class='color-noir'>ANALYTICAL SOLUTIONS</span> <span class='color-rouge'>FOR IMPACT</span>",
        "services.banner_sub": "Consultancy sales, humanitarian training and field logistics in hard-to-reach areas.",
        "services.expertise_label": "Our Skills",
        "services.expertise_title_part1": "<span class='color-noir'>A pluridisciplinary</span>",
        "services.expertise_title_part2": "<span class='color-rouge'>expertise</span>",
        "services.banner_giant1": "EPHOD",
        "services.banner_giant2": "CONSULTING",
        "services.banner_desc": "<strong style='font-size: 2.2em; display: inline-block; letter-spacing: 2px; text-transform: uppercase; font-weight: 800; text-align: center; width: 100%; background: linear-gradient(to right, #ffffff, #b01a47, #ffffff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; filter: drop-shadow(0 2px 4px rgba(0,0,0,0.3));'>Analytical Solutions for Lasting Impact</strong>",
        "portfolio.banner_title": "<span class='color-noir'>OUR IMPACT</span> <span class='color-rouge'>CAPITAL</span>",

        "srv.s1_title": "STUDIES & RESEARCH",
        "srv.s1_desc": "Baseline, market studies, needs assessments (MSNA) and complete institutional diagnostics.",
        "srv.s2_title": "INDEPENDENT EVALUATION",
        "srv.s2_desc": "Mid-term and final evaluations according to OECD-DAC and CHS Alliance criteria.",
        "srv.s3_title": "SECURE CASH SERVICES",
        "srv.s3_desc": "Support for cash interventions (Mobile Money, remittances) in hard-to-reach areas.",
        "srv.s4_title": "TRAINING & CAPACITIES",
        "srv.s4_desc": "Capacity building in MEAL, project management and data tools (Kobo/ODK).",
        "srv.s5_title": "FIELD LOGISTICS",
        "srv.s5_desc": "Last-mile support in fragile geographical zones and complex access areas.",
        "srv.s6_title": "CROSS-CUTTING INTEGRATION",
        "srv.s6_desc": "Gender, Protection, Inclusion (AAP) analyses and Conflict Sensitivity studies.",
        "srv.s7_title": "SECURE CASH SERVICES",
        "srv.s7_desc": "Support for cash interventions (Mobile Money, Remittances) and market studies in difficult areas.",
        "srv.s8_title": "FIELD LOGISTICS",
        "srv.s8_desc": "Last-mile support, GIS mapping, and digital collection in fragile and emergency contexts.",
        "srv.s9_title": "GENDER, PROTECTION & AAP",
        "srv.s9_desc": "Mainstreaming Gender, Protection, Inclusion, and Conflict Sensitivity analyses into every mission.",

        "services.btn_more": "LEARN MORE <i class='bi bi-arrow-right ms-2'></i>",
        "home.method_desc2": "Our interventions are structured according to the most demanding global standards to guarantee the efficiency, transparency, and accountability of each mission.",
        "services.oecd_badge": "MAJOR FRAMEWORK",
        "services.oecd_title": "OECD-DAC CRITERIA",
        "services.oecd_desc": "The cornerstone of development evaluation. We integrate the 5 fundamental pillars into every report:",
        "services.oecd_p1": "Relevance",
        "services.oecd_p2": "Effectiveness",
        "services.oecd_p3": "Efficiency",
        "services.oecd_p4": "Impact",
        "services.oecd_p5": "Sustainability",

        "services.chs_badge": "HUMANITARIAN STANDARD",
        "services.chs_title": "CHS ALLIANCE",
        "services.chs_desc": "Our unconditional commitment to accountable aid centered on the dignity of affected populations:",
        "services.chs_p1": "Zero Tolerance Commitment (PSEA)",
        "services.chs_p2": "Accountability mechanisms (AAP)",
        "services.chs_p3": "Continuous Learning & Improvement",

        "srv.modal_need": "Client Need",
        "srv.modal_how": "Our Methodology",
        "srv.modal_value": "Added Value",
        "srv.modal_close": "Close",

        "srv.s1_need": "Requirement for evidence-based and reliable data to guide humanitarian and development interventions.",
        "srv.s1_how": "Deployment of field surveys (MSNA, Baseline) via digital tools (Kobo) and rigorous statistical analysis.",
        "srv.s1_value": "A solid decision-making basis to maximize funding efficiency and beneficiary targeting.",

        "srv.s2_need": "Need for a neutral, high-level external vision to validate program impact.",
        "srv.s2_how": "Mid-term and final evaluations based on OECD-DAC criteria: relevance, effectiveness, impact.",
        "srv.s2_value": "Actionable strategic recommendations for continuous improvement of project cycles.",

        "srv.s3_need": "Securing cash transfers in remote or landlocked areas.",
        "srv.s3_how": "Network of local agents and mobile solutions (Mobile Money) adapted to security-fragile contexts.",
        "srv.s3_value": "Guarantee of financial aid delivery to the most vulnerable populations in complete safety.",

        "srv.s4_need": "Strengthening local skills to ensure the sustainability of project achievements.",
        "srv.s4_how": "Bespoke training in project management, MEAL, and protection standards (PSEA/AAP).",
        "srv.s4_value": "Empowerment of local partners and compliance with international standards (CHS).",

        "srv.s5_need": "Operational support for last-mile logistics in difficult geographical areas.",
        "srv.s5_how": "Supply chain management and agile deployment of mobile teams.",
        "srv.s5_value": "Reduction of intervention times and control of logistical costs in complex environments.",

        "srv.s6_need": "Systematic integration of gender and protection issues in all project phases.",
        "srv.s6_how": "Vulnerability analyses, conflict sensitivity studies, and inclusion audits.",
        "srv.s6_value": "Reduction of protection risks and promotion of the dignity and equity of beneficiaries.",

        "portfolio.banner_title": "<span class='color-noir'>OUR IMPACT</span> <span class='color-rouge'>CAPITAL</span>",
        "portfolio.banner_sub": "Over a decade of operational expertise supporting humanitarian and development partners.",
        "port.all": "All",
        "port.cat1": "Studies & Evaluation",
        "port.cat2": "Advisory & Strategy",
        "port.cat3": "Logistics & Cash",
        "port.more": "Mission details",
        "port.modal_download": "Project Sheet",
        "port.modal_challenge": "The Challenge",
        "port.modal_strategy": "The Strategy",
        "port.modal_impact_title": "The Impact",

        "port.p1_title": "ProGERIM II Project", 
        "port.p1_client": "GIZ (German Cooperation)", 
        "port.p1_zone": "Lualaba & Haut-Katanga", 
        "port.p1_date": "2024-2026",
        "port.p1_context": "Technical support for improving transparency and management of subnational mining revenues in DRC. Data collection via LQAS methodology.",
        "port.p1_solution": "Diagnostic of ETDs and institutional capacity building on mining governance.",
        "port.p1_impact": "Increased transparency and better redistribution of mining royalties at the local level.",

        "port.p2_title": "Market & Cash Risk Study", 
        "port.p2_client": "JRS (Jesuit Refugee Service)", 
        "port.p2_zone": "Kayna & Lubero", 
        "port.p2_date": "2026",
        "port.p2_context": "Assess the feasibility of cash transfers and protection risks related to cash interventions in North Kivu.",
        "port.p2_solution": "Household survey, local market analysis, and mapping of financial service providers.",
        "port.p2_impact": "Optimization of humanitarian assistance through secure and dignified cash modalities.",

        "port.p3_title": "Integrated Response Walikale", 
        "port.p3_client": "Umoja in Action", 
        "port.p3_zone": "Walikale & Bunyakiri", 
        "port.p3_date": "2026",
        "port.p3_context": "Baseline study for a rapid response project for displaced populations affected by conflicts.",
        "port.p3_solution": "Multisectoral Needs Assessment (MSNA) and conflict sensitivity analysis.",
        "port.p3_impact": "Accurate targeting of beneficiaries and reduction of community tensions.",

        "port.p4_title": "Christian Aid PDM Survey", 
        "port.p4_client": "Christian Aid", 
        "port.p4_zone": "Kalehe (South Kivu)", 
        "port.p4_date": "2026",
        "port.p4_context": "Post-distribution monitoring (PDM) to assess beneficiary satisfaction and aid utilization.",
        "port.p4_solution": "Implementation of a feedback and accountability mechanism (AAP).",
        "port.p4_impact": "Continuous improvement of humanitarian aid quality.",

        "port.p5_title": "ERM Consortium Needs Assessment", 
        "port.p5_client": "SCI, MEDAIR, CARE, IMC", 
        "port.p5_zone": "Ituri & North Kivu", 
        "port.p5_date": "2023",
        "port.p5_context": "Rapid multisectoral assessment (ERM) for populations victims of natural disasters and conflicts.",
        "port.p5_solution": "Agile deployment of data collection teams in hard-to-reach areas.",
        "port.p5_impact": "Rapid and evidence-based humanitarian response.",

        "port.p6_title": "Education Audit (Covid-19)", 
        "port.p6_client": "UNICEF / SCI", 
        "port.p6_zone": "16 Provinces (DRC)", 
        "port.p6_date": "2022",
        "port.p6_context": "Final evaluation of the impact of emergency educational measures during the pandemic.",
        "port.p6_solution": "Project performance evaluation according to OECD-DAC criteria.",
        "port.p6_impact": "Critical recommendations for the resilience of the Congolese educational system.",
        "port.p7_title": "Stakeholder ID", "port.p7_client": "ULB", "port.p7_zone": "Goma", "port.p7_date": "2024",
        "port.p8_title": "Proj Management Training", "port.p8_client": "RACOJ North Kivu", "port.p8_zone": "Goma", "port.p8_date": "2026",
        "port.p9_title": "Rapid Needs UVIRA & RUZIZI", "port.p9_client": "GHOVODI & ODH", "port.p9_zone": "South Kivu", "port.p9_date": "2026",
        "port.p10_title": "Systemic Diagnosis WALIKALE", "port.p10_client": "GHOVODI & ODH", "port.p10_zone": "North Kivu", "port.p10_date": "2025",
        "port.p11_title": "Media Survey M4D", "port.p11_client": "La Benevolencija", "port.p11_zone": "Rutshuru, Lubero, Masisi", "port.p11_date": "2023",
        "port.p12_title": "UKWELI BILA CHUKI Audit", "port.p12_client": "La Benevolencija", "port.p12_zone": "North Kivu", "port.p12_date": "2024",
        "port.p13_title": "IDPs Employment Study", "port.p13_client": "JRS", "port.p13_zone": "Masisi", "port.p13_date": "2019",
        "port.p14_title": "Final Education Eval", "port.p14_client": "UNICEF / SCI", "port.p14_zone": "8 Provinces (DRC)", "port.p14_date": "2023",
        "port.p15_title": "Mining Royalty Study", "port.p15_client": "GIZ / ETD", "port.p15_zone": "Haut-Katanga", "port.p15_date": "2023",
        "port.p16_title": "Final Eval FIZI", "port.p16_client": "ODH", "port.p16_zone": "Fizi (South Kivu)", "port.p16_date": "2024",
        "port.p17_title": "Mid-term Malnutrition Eval", "port.p17_client": "RACOJ NK (DKH)", "port.p17_zone": "Kasai Central", "port.p17_date": "2022",
        "port.p18_title": "FSP M&E System", "port.p18_client": "Mercy Corps", "port.p18_zone": "Bukavu", "port.p18_date": "2017",
        "port.p19_title": "Refugees Value Chains", "port.p19_client": "UNHCR", "port.p19_zone": "North/South-Ubangi, Bas-Uele", "port.p19_date": "2024",
        "port.p20_title": "Youth Employability", "port.p20_client": "Follereau Foundation", "port.p20_zone": "Mali (Segou)", "port.p20_date": "2019",

        "ongoing.page_title": "Mission Monitoring",
        "ongoing.page_subtitle": "Progress status of our current consultancy contracts for 2026.",
        "ongoing.progress": "Progress",
        "ongoing.proj1_title": "ProGERIM II Mission (GIZ)",
        "ongoing.proj1_desc": "Improving mining revenue transparency for ETDs in Lualaba and Haut-Katanga. LQAS collection ongoing.",
        "ongoing.proj2_title": "JRS Evaluation (Kayna/Lubero)",
        "ongoing.proj2_desc": "Gender, Inclusion and Conflict Sensitivity analysis. Lubero field mission at 85%.",
        "ongoing.proj3_title": "SONAHU Audit (North Kivu)",
        "ongoing.proj3_desc": "Governance audit and OHADA compliance for partner SONAHU.",
        "ongoing.proj4_title": "Umoja in Action (MEAL)",
        "ongoing.proj4_desc": "M&E support for multisectoral response in Walikale.",

        "careers.banner_title": "<span class='color-noir'>JOB</span> <span class='color-rouge'>OPENINGS</span>",
        "careers.banner_sub": "EPHOD recruits bilingual experts for its research and training missions.",
        "careers.job1_title": "Senior Consultants",
        "careers.job1_desc": "Experts in strategic planning and OECD evaluation. CHS standard knowledge required.",
        "careers.policy_label": "Governance & Ethics",
        "careers.policy_title": "<span class='color-noir'>Our Human Resources</span> <span class='color-rouge'>Policy</span>",
        "careers.p_legal_title": "Legal Commitment",
        "careers.policy_legal": "EPHOD Consulting's HR management is strictly governed by OHADA law and the DRC Labor Code. We guarantee full social protection and a safe working environment.",
        "careers.p_equity_title": "Equity & Diversity",
        "careers.policy_equity": "Recruitment is based on transparency, equal opportunity and non-discrimination. Each talent is evaluated solely on their technical skills and their adherence to our values of excellence.",
        "careers.apply": "Send Application",

        "contact.banner_eyebrow": "CONTACT & LOCATIONS",
        "contact.banner_title": "<span class='color-noir'>National</span> <span class='color-rouge'>Presence</span>",
        "contact.banner_sub": "Headquarters in Kinshasa, tech centers in Goma and Beni.",
        "contact.label_offices": "Our Offices",
        "contact.offices_title": "<span class='color-noir'>Where to</span> <span class='color-rouge'>Find Us?</span>",
        "contact.addr_kin_label": "Kinshasa (HQ)",
        "contact.addr_kin_text": "Ma Campagne Qrt, Kapaya Ave N°03,<br>Ngaliema Commune",
        "contact.addr_goma_label": "Goma (Office)",
        "contact.addr_goma_text": "Kyeshero Qrt, Kituku Ave N°13",
        "contact.addr_beni_label": "Beni (Office)",
        "contact.addr_beni_text": "RN4, Opienge Ave N°6",
        "contact.kin_tab": "KINSHASA (HQ)",
        "contact.goma_tab": "GOMA",
        "contact.beni_tab": "BENI",
        "contact.map_tag_kin": "OUR HEADQUARTERS — KINSHASA",
        "contact.map_tag_goma": "OFFICE — GOMA",
        "contact.map_tag_beni": "OFFICE — BENI",
        "contact.fast_contacts_title": "Quick Contacts",
        "contact.form_title": "<span class='color-noir'>Send us a</span> <span class='color-rouge'>Message</span>",
        "contact.form_name": "Full Name",
        "contact.form_email": "Email",
        "contact.form_msg": "Your message",
        "contact.form_send": "Send",
        "contact.map_tag": "OUR HEADQUARTERS — KINSHASA",
        "srv_m1.title": "STUDIES & RESEARCH",
        "srv_m1.subtitle": "OUR ANALYTICAL EXPERTISE",
        "srv_m1.intro": "EPHOD Consulting deploys rigorous methodologies to inform strategic decision-making:",
        "srv_m1.i1_title": "Baseline & Endline Surveys:",
        "srv_m1.i1_desc": "Establishing baseline situations and final measurement of indicators.",
        "srv_m1.i2_title": "Market & Feasibility Studies:",
        "srv_m1.i2_desc": "Analysis of supply, demand, and local value chains.",
        "srv_m1.i3_title": "Institutional Diagnostics:",
        "srv_m1.i3_desc": "Audit of organizational and operational capacities.",
        "srv_m1.i4_title": "Sectoral Analyses:",
        "srv_m1.i4_desc": "Public Health, Mining, Agriculture, and WASH.",
        "srv_m2.title": "INDEPENDENT EVALUATIONS",
        "srv_m2.subtitle": "ACCOUNTABILITY & PERFORMANCE",
        "srv_m2.intro": "We evaluate the impact of your programs according to the highest international standards:",
        "srv_m2.i1_title": "OECD-DAC Criteria:",
        "srv_m2.i1_desc": "Analysis of relevance, effectiveness, efficiency, impact, and sustainability.",
        "srv_m2.i2_title": "Real-Time Evaluations:",
        "srv_m2.i2_desc": "Technical adjustments during execution to optimize impact.",
        "srv_m2.i3_title": "Quality Audit (CHS):",
        "srv_m2.i3_desc": "Verification of compliance with Core Humanitarian Standards.",
        "srv_m3.title": "MONETARY SERVICES",
        "srv_m3.subtitle": "AGILE CASH SOLUTIONS",
        "srv_m3.intro": "EPHOD facilitates secure monetary transfers in high-risk zones:",
        "srv_m3.i1_title": "Mobile Money Displacement:",
        "srv_m3.i1_desc": "Flow management via local operators in fragile areas.",
        "srv_m3.i2_title": "PDM Verification:",
        "srv_m3.i2_desc": "Monitoring funds utilization by beneficiaries.",
        "srv_m3.i3_title": "Vendor Mapping:",
        "srv_m3.i3_desc": "Identification and contracting of local traders.",
        "srv_m4.title": "TRAINING & CAPACITATION",
        "srv_m4.subtitle": "SKILLS DEVELOPMENT",
        "srv_m4.intro": "Capacity building for your field teams and local partners:",
        "srv_m4.i1_title": "Project Cycle & MEAL:",
        "srv_m4.i1_desc": "Design of logical frameworks and M&E systems.",
        "srv_m4.i2_title": "Digital Data Collection:",
        "srv_m4.i2_desc": "Advanced training on KoboToolbox, ODK, and PowerBI.",
        "srv_m4.i3_title": "Governance & Management:",
        "srv_m4.i3_desc": "Humanitarian leadership and management in crisis contexts.",
        "srv_m5.title": "FIELD LOGISTICS",
        "srv_m5.subtitle": "OPERATIONAL SUPPORT",
        "srv_m5.intro": "Optimizing your supply chain in hostile environments:",
        "srv_m5.i1_title": "Last-Mile Delivery:",
        "srv_m5.i1_desc": "Delivery of critical goods (medicine, inputs) to isolated areas.",
        "srv_m5.i2_title": "Warehouse Management:",
        "srv_m5.i2_desc": "Storage and inventory assisted by digital tools.",
        "srv_m5.i3_title": "Deployment Support:",
        "srv_m5.i3_desc": "Rapid setup of guest houses and mobile offices.",
        "srv_m6.title": "CROSS-CUTTING INTEGRATION",
        "srv_m6.subtitle": "EQUITY & SENSITIVITY",
        "srv_m6.intro": "Ensuring inclusion and dignity in all project phases:",
        "srv_m6.i1_title": "Gender & Inclusion Analysis:",
        "srv_m6.i1_desc": "Integration of specific needs of women, children, and people with disabilities.",
        "srv_m6.i2_title": "Conflict Sensitivity:",
        "srv_m6.i2_desc": "'Do No Harm' approach to avoid exacerbating local tensions.",
        "srv_m6.i3_title": "Accountability (AAP):",
        "srv_m6.i3_desc": "Implementation of complaint and feedback mechanisms for beneficiaries.",

        "footer.contact_title": "Contact",
        "footer.desc": "Humanitarian and Development consultancy firm (RCCM CD/KNG/RCCM/25-B-03958).",
        "footer.rights": "All rights reserved.",
        "footer.made": "EPHOD CONSULTING SARL",
        "footer.addr_kin": "Kinshasa: Q. Ma Campagne, Av. Kapaya N°03, C/Ngaliema",
        "footer.addr_goma": "Goma: Q. Kyeshero, Av. Kituku N°13",
        "footer.addr_beni": "Beni: RN4, Face ENERA, Entrée KVG, N°6",

        "about.rccm": "RCCM: CD/KNG/RCCM/25-B-03958",
        "about.idnat": "NAT ID: 01-H5300-N88322C",
        "about.ungm": "UNGM: 1175536",
        "about.nif": "Tax: A2559012X",
        "about.bank_title": "Banking Details",
        "about.bank_acc": "USD Account: 00011-15066-62002620265-77",
        "about.bank_swift": "Swift: BCDCCDKIxxx",

        "about.pillar1_title": "Build",
        "about.pillar1_desc": "Organizational resilience in complex contexts.",
        "about.pillar2_title": "Catalyze",
        "about.pillar2_desc": "International standard operational performance.",
        "about.pillar3_title": "Transform",
        "about.pillar3_desc": "Your strategic ambitions into concrete and sustainable impacts.",

        "about.role_dg_desc": "Visionary and guarantor of EPHOD Consulting's strategic excellence.",
        "about.role_ops_desc": "Expert in field coordination and deployment in complex environments.",

        "careers.p_dev_title": "Continuous Development",
        "careers.policy_dev": "Regular training, mentoring by senior experts and growth opportunities within high value-added missions throughout the DRC.",

        "careers.jobs_label": "OPEN POSITIONS",
        "careers.jobs_title": "Current <span>Opportunities</span>",
        "careers.job1_title": "Consultants & Independent Experts",
        "careers.job1_desc": "Network of specialized international experts (Health, Education, Protection, WASH, MEAL). ISO/CHS knowledge recommended.",
        "careers.job1_req1": "Minimum Master's degree in social sciences, public health or equivalent",
        "careers.job1_req2": "5+ years experience in humanitarian contexts",
        "careers.job1_req3": "Proficiency in KoboToolbox, SPSS or Stata",
        "careers.job1_req4": "Excellent writing skills (reports & proposals)",
        
        "careers.job2_title": "Research Technicians",
        "careers.job2_desc": "In charge of data collection (KoboToolbox) and proposal/report drafting. Bilingualism required.",
        "careers.job2_req1": "Bachelor's in statistics, economics or social sciences",
        "careers.job2_req2": "Experience in digital data collection",
        "careers.job2_req3": "Ability to work in hard-to-reach areas",
        "careers.job2_req4": "Knowledge of LQAS/MSNA protocols appreciated",

        "careers.job_req_title": "Required profile:",
        "careers.job_apply_btn": "Apply now",

        "careers.form_label": "APPLICATION",
        "careers.form_title": "Join <span>Excellence</span>",
        "careers.form_sub": "Submit your complete application. Our HR team will review your profile within 72 business hours.",
        "careers.lbl_name": "Full name *",
        "careers.ph_name": "Ex: John DOE",
        "careers.lbl_email": "Email address *",
        "careers.lbl_phone": "Phone *",
        "careers.lbl_pos": "Target position *",
        "careers.opt_def": "— Select a position —",
        "careers.opt_1": "Consultant & Independent Expert",
        "careers.opt_2": "Research Technician",
        "careers.opt_3": "Spontaneous application",
        "careers.lbl_cv": "Curriculum Vitae (PDF only) *",
        "careers.cv_drop": "Drop your CV here or <strong>click to browse</strong>",
        "careers.cv_format": "PDF format — Max 5 MB",
        "careers.lbl_letter": "Cover letter *",
        "careers.ph_letter": "Describe your motivation, key skills and availability...",
        "careers.lbl_lk": "LinkedIn Profile (optional)",
        "careers.lbl_avail": "Availability",
        "careers.avail_1": "Immediate",
        "careers.avail_2": "Within 1 month",
        "careers.avail_3": "Within 3 months",
        "careers.avail_4": "Negotiable",
        "careers.btn_submit": "Submit my application",
        "careers.form_disc": "By submitting this form, you agree that your data will be processed in accordance with our privacy policy.",

        "ongoing.banner_title": "<span class='color-noir'>ONGOING</span> <span class='color-rouge'>MISSIONS</span>",
        "ongoing.ticker_label": "LIVE LOG",
        "ongoing.tick1": "ProGERIM Mission: LQAS data collection phase completed in 3 ETDs in Lualaba...",
        "ongoing.tick2": "JRS Mission: Evaluation team deployed in Kayna and Lubero...",
        "ongoing.tick3": "SONAHU Audit: OHADA compliance review 40% complete...",
        "ongoing.tick4": "Umoja in Action: MEAL system configured on KoboToolbox...",
        "ongoing.tick5": "EPHOD Logistics: Technical convoy arrived in Beni...",

        "ongoing.badge_action": "ONGOING ACTION",
        "ongoing.proj1_title": "ProGERIM II Mission (GIZ)",
        "ongoing.proj1_desc": "Improving mining revenue transparency for ETDs in Lualaba and Haut-Katanga. LQAS collection ongoing.",
        "ongoing.p1_meta1": "Lualaba & Haut-Katanga",
        "ongoing.p1_meta2": "GIZ / ProGERIM",

        "ongoing.badge_terrain": "FIELD MISSION",
        "ongoing.proj2_title": "JRS Evaluation (Kayna/Lubero)",
        "ongoing.proj2_desc": "Gender, Inclusion and Conflict Sensitivity Analysis. Lubero field mission 85% underway.",
        "ongoing.p2_meta1": "North Kivu (Lubero)",
        "ongoing.p2_meta2": "JRS DR CONGO",

        "ongoing.badge_audit": "EPHOD AUDIT",
        "ongoing.proj3_title": "SONAHU Audit (North Kivu)",
        "ongoing.proj3_desc": "Governance and OHADA compliance audit for our partner SONAHU.",
        "ongoing.p3_meta1": "North Kivu",
        "ongoing.p3_meta2": "SONAHU A.S.B.L",

        "ongoing.badge_support": "MEAL SUPPORT",
        "ongoing.proj4_title": "Umoja in Action (MEAL)",
        "ongoing.proj4_desc": "Support to the monitoring and evaluation system for the multisectoral response in Walikale.",
        "ongoing.p4_meta1": "Walikale Territory",
        "ongoing.p4_meta2": "Umoja in Action",

        "ongoing.progress": "Operational Progress",

        "ongoing.kpi1": "Active Missions",
        "ongoing.kpi2": "Deployed Experts",
        "ongoing.kpi3": "Provinces Covered",
        "ongoing.kpi4": "Partner Satisfaction",

        "footer.nav_title": "NAVIGATION",
        "footer.offices_title": "OFFICES & CONTACT",
        "footer.kin_label": "KINSHASA (HQ)",
        "footer.goma_label": "GOMA",
        "footer.beni_label": "BENI",
        "footer.direct_label": "DIRECT CONTACT"
    }
};

let currentLang = localStorage.getItem('ephod_lang') || 'fr';

function toggleLanguage() {
    currentLang = currentLang === 'fr' ? 'en' : 'fr';
    window.currentLang = currentLang; // ensure global access is updated
    localStorage.setItem('ephod_lang', currentLang);
    updateLangUI();
    applyTranslations();
    if (window.resetAllTypewriters) { window.resetAllTypewriters(); }
}

window.translations = translations;
window.currentLang = currentLang;

function updateLangUI() {
    const langBtn = document.getElementById('lang-toggle-text');
    if (langBtn) langBtn.innerText = currentLang.toUpperCase();
}

function applyTranslations() {
    const elements = document.querySelectorAll('[data-i18n]');
    const data = translations[currentLang];
    if (!data) return;

    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (data[key]) {
            const val = data[key];
            if (el.hasAttribute('data-text')) { el.setAttribute('data-text', val); }
            if (el.hasAttribute('data-html')) { el.setAttribute('data-html', val); }
            
            // TYPEWRITER SOURCE: Always store the latest translation in a data attribute
            if (el.classList.contains('chained') || el.classList.contains('typewriter-scroll')) {
                el.setAttribute('data-typewriter-text', val);
            }

            // PROTECT INNERHTML: Don't overwrite if it's currently typing
            if (!el.classList.contains('typing-active') && !el.classList.contains('chained')) {
                el.innerHTML = val;
            }
        }
    });

    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
    placeholders.forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (data[key]) { el.placeholder = data[key]; }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    updateLangUI();
    applyTranslations();
});

window.addEventListener('storage', (event) => {
    if (event.key === 'ephod_lang') {
        const newLang = event.newValue;
        if (newLang && newLang !== window.currentLang) {
            window.currentLang = newLang;
            updateLangUI();
            applyTranslations();
            if (window.resetAllTypewriters) { window.resetAllTypewriters(); }
        }
    }
});
